package org.foi.uzdiz.bradinovi.podaci;

public enum Kljucevi {
    IDULOGE, IMEULOGE,
    IDOSOBE, IMEPREZIMEOSOBE,
    IDPROGRAMA, NAZIVPROGRAMA, POCETAK, KRAJ, NAZIVDATOTEKE,
    IDEMISIJE, NAZIVEMISIJE, TRAJANJEEMISIJE, SUDIONICIEMISIJE, VRSTAEMISIJE,
    IDVRSTEEMISIJE, NAZIVVRSTEEMISIJE, REKLAMEEMISIJE, TRAJANEREKLAMA
}
